### ISSUE TITLE
Get More Backlinks

### ISSUE THREAD

**Issue by Corona-Media** [Corona-Media/corona-media.github.io#17]
Try Requesting them from other websites.

**Comment by steph-hickman9** [comment]
Hi there! I am interested in contributing, but am unsure exactly what this issue is referring to. Do you want more links for the random activity generator? I can absolutely find links for the cool activities already listed that don't have one, and possibly add more activities. If this isn't what you meant by backlinks, please let me know how I can help!

**Comment by IlanLuci** [comment]
> Hi there! I am interested in contributing, but am unsure exactly what this issue is referring to. Do you want more links for the random activity generator? I can absolutely find links for the cool activities already listed that don't have one, and possibly add more activities. If this isn't what you meant by backlinks, please let me know how I can help!

By backlinks I meant links from other websites for SEO. But yes I am open to ideas for new activities and/or articles and videos.

**Comment by TriinK** [comment]
I'd be happy to contribute to this aswell
